# Generated by Django 2.0 on 2019-12-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191213_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='other',
        ),
    ]
