# Generated by Django 2.0 on 2019-12-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_discover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discover',
            name='title',
        ),
    ]
