# Generated by Django 2.0 on 2019-12-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191217_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
