# Generated by Django 2.0 on 2019-12-17 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191217_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newscomment', to='news.News'),
        ),
    ]
