# Generated by Django 2.0 on 2019-12-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20191217_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomment',
            old_name='content',
            new_name='comment',
        ),
    ]
