# Generated by Django 2.0 on 2019-12-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20191217_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to', models.URLField()),
                ('priority', models.IntegerField()),
                ('image_url', models.URLField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ['-pub_time']},
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
