# Generated by Django 2.0 on 2020-01-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='cellphone',
            field=models.CharField(default='空', max_length=200),
        ),
        migrations.AlterField(
            model_name='party',
            name='memo',
            field=models.CharField(default='空', max_length=200),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(default='空', max_length=200),
        ),
    ]
