# Generated by Django 2.0 on 2020-01-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20200122_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='money',
            field=models.CharField(default='空', max_length=200),
        ),
    ]
