# Generated by Django 2.0 on 2020-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='money',
            field=models.CharField(default='', max_length=200),
        ),
    ]
