# Generated by Django 2.0 on 2019-12-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='isp',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='content',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
